### DISCUSSION TITLE
Team Logo - Card Error

### DISCUSSION THREAD

**Discussion by mpjanofsky** [vasqued2/ha-teamtracker#133] [Q&A]
This integration is awesome - I'm looking forward to the USL Championship Soccer season kicking off in March!

I've tried to create a standings card following the examples provided for the English Premier league and I've run into trouble with the image column. Both the API and the sensor I've created seem to have the same data, so I'm not sure what I'm missing. I created the EPL sensor and card from the examples and the images displayed as expected.

My sensor config:
```
- platform: rest
    name: USL Championship Standings
    scan_interval: 43200
    resource: https://site.web.api.espn.com/apis/v2/sports/soccer/usa.usl.1/standings?type=0&level=0
    value_template: "{{ now() }}"
    json_attributes_path: "$['children'][0]['standings']"
    json_attributes:
        - entries
```

Card Config:
```
type: custom:flex-table-card
title: USL Championship - Eastern Conference
sort_by: place
entities:
  include: sensor.usl_championship_standings
columns:
  - name: '#'
    id: place
    data: entries
    modify: x.stats[10].value
    align: center
  - name: Logo
    data: entries
    modify: '''<img src="'' + x.team.logos[0].href + ''"style="width: 100%">'''
    align: center
  - name: Team
    data: entries
    modify: x.team.shortDisplayName
  - name: GP
    data: entries
    modify: x.stats[0].value
    align: center
  - name: W
    data: entries
    modify: x.stats[5].value
    align: center
  - name: L
    data: entries
    modify: x.stats[1].value
    align: center
  - name: T
    data: entries
    modify: x.stats[4].value
    align: Pts
  - name: GD
    data: entries
    modify: x.stats[2].value
    align: center
  - name: PTS
    data: entries
    modify: x.stats[3].value
    align: center
css:
  tbody tr td:nth-child(2): 'width: 10%;'
```

This produces an error of "Cannot read properties of undefined (reading '0')" 

If I remove the colum for logo, the card works exactly as expected. Hoping someone might catch something I'm missing!
