### DISCUSSION TITLE
What to do with POST games

### DISCUSSION THREAD

**Discussion by Ragetti13** [vasqued2/ha-teamtracker#164] [Q&A]
Hi all,

I've tried searching around for an answer for this but I am struggling to find a solution that works. My issue is that I have 11 entities for teams and once an international tournament is finished the final result sits on my dashboard permanently. What do you all do for showing cards and hiding them once they have finished? I have the auto-entities card and filtering out the not_founds which works great, but I have an international team that is always stuck showing with the post-game status.

Any thoughts/ideas would be really helpful.

James

**Comment by vasqued2** [comment]
You should be able to add one more test in the template for the `date` attribute in the sensor, compare it to the current date, and then once it gets too far in the past, don't display it.

**Comment by Combatchuck** [comment]
Here is what I do with the Braves. I don't want the card there all day, so I figure 4 hours is enough

sensors.yaml - reload after you edit

```
      braves_not_post_duration:
        friendly_name: "Braves Not Post Duration"
        value_template: >
          {% if states('sensor.braves') != 'POST' %}
            {{ as_timestamp(now()) - as_timestamp(states.sensor.braves.last_changed) }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "seconds"
      
      braves_not_post_4_hours:
        friendly_name: "Braves Not POST for 4 Hours"
        value_template: "{{ states('sensor.braves_not_post_duration') | int >= 14400 }}" 
```

then start the card with this condition

```
type: conditional
conditions:
  - condition: state
    entity: sensor.braves_not_post_4_hours
    state: 'True'
  - condition: or
    conditions:
      - condition: state
        entity: sensor.braves_not_post_duration
        state: Current
      - condition: state
        entity: sensor.braves
        state_not: NOT_FOUND
      - condition: state
        entity: sensor.braves
        state_not: unavailable
      - condition: state
        entity: sensor.braves
        state: IN
```
