### DISCUSSION TITLE
I love this integration

### DISCUSSION THREAD

**Discussion by uSlackr** [vasqued2/ha-teamtracker#30] [General]
I've always wanted a goal light in my house since I saw one sold by the NHL.  This lets me do it for all my teams.  Very cool

To that end, I am using my undercounter led strip as the notification light.  But, it has a normal mode.  I need to be able to save the current config (color,brightness) and restore after the notification.  I tried using this:
```
service: scene.create
data:
  scene_id: score_save
  snapshot_entities: light.island_led_strip
```
followed by my flashing script, followed by this:
```
service: scene.create
data:
  scene_id: score_save
  snapshot_entities: light.island_led_strip
```
But I lost the color.  Would you know if this is the right approach?

**Comment by uSlackr** [comment]
I think I solved it.  The issue is my led strip doesn't change color without an off/on event.  So, I added two toggles at the end to ensure it comes back on with the saved scene color and that is stays on if on and off if off.

**Comment by uSlackr** [comment]
My next desire is to have one automation for all four teams I track.  They all have unique colors.  So I'm trying this: name the trigger ids based on the color, then reference the trigger id on the turn on code.  

```
platform: state
entity_id: sensor.psu_fb
attribute: team_score
id: blue
```
and 
```
service: light.turn_on
data:
  transition: 1
  color_name:
    {{trigger.id}}
target:
  entity_id: light.island_led_strip
```
This could also be done with a trigger variable. 
Of course I cannot test it manually since the trigger.id isn't set
