### ISSUE TITLE
NHL Metro Division

### ISSUE THREAD

**Issue by SwaggerRight** [vasqued2/ha-teamtracker#212]
I noticed that the ESPN API for the NHL has changed. They no longer follow the same order for the various stats. For instance 'Games Played' for the Washington Capitals is the 4th stat, but the same stat for the Hurricanes is the 3rd stat. Is there another way to identify the stats other than the order...like by the 'name' value?

**Comment by SwaggerRight** [comment]
Nevermind. I figured it out. ESPN seems to change the order of the stats, but the names of the stats stays pretty consistent. You may want to update the example in the Wiki for the NHL Metro division to this instead:


type: custom:flex-table-card
title: NHL Metro Div Standings
sort_by: place
entities:
  include: sensor.nhl_standings
columns:
  - name: Logo
    data: entries
    modify: '''<img src="'' + x.team.logos[0].href + ''"style="width: 100%">'''
    align: center
  - name: Team
    data: entries
    modify: x.team.name
  - name: GP
    data: entries
    modify: >-
      (x.stats.find(s => s.name === "gamesPlayed") || {}).value
    align: center
  - name: W
    data: entries
    modify: >-
      (x.stats.find(s => s.name === "wins") || {}).value
    align: center
  - name: L
    data: entries
    modify: >-
      (x.stats.find(s => s.name === "losses") || {}).value
    align: center
  - name: OTL
    data: entries
    modify: >-
      (x.stats.find(s => s.name === "overtimeLosses") || {}).value
    align: center
  - name: Pts
    data: entries
    modify: >-
      (x.stats.find(s => s.name === "points") || {}).value
    align: center
css:
  tbody tr td:nth-child(1): 'width: 10%;'

**Comment by SwaggerRight** [comment]
Nevermind. I figured it out. You may want to update the example for the Metro division to this instead:

 ```
 - type: custom:flex-table-card
    title: NHL Metro Div Standings
    sort_by: place
    entities:
      include: sensor.nhl_standings
    columns:
      - name: Logo
        data: entries
        modify: "'<img src=\"' + x.team.logos[0].href + '\"style=\"width: 100%\">'"
        align: center
      - name: Team
        data: entries
        modify: x.team.name
      - name: GP
        data: entries
        modify: >-
          (x.stats.find(s => s.name === "gamesPlayed") || {}).value
        align: center
      - name: Pts
        data: entries
        modify: >-
          (x.stats.find(s => s.name === "points") || {}).value
        align: center
      - name: Playoff Seed
        data: entries
        modify: >-
         (x.stats.find(s => s.name === "playoffSeed") || {}).value
        align: center
      - name: Record
        data: entries
        modify: >-
          (x.stats.find(s => s.name === "overall") || {}).summary
        align: center
      - name: STRK
        data: entries
        modify: >-
         (x.stats.find(s => s.name === "streak") || {}).value
        align: center
    css:
      tbody tr td:nth-child(1): "width: 10%;"
    view_layout:
      position: main
```
