### ISSUE TITLE
Canadian Football League (CFL)

### ISSUE THREAD

**Issue by jasper502** [vasqued2/ha-teamtracker#216]
To my surprise the CFL is on ESPN:

https://site.api.espn.com/apis/site/v2/sports/football/cfl/scoreboard

Looks like just and add to the dropdown list.

**Comment by vasqued2** [comment]
Configure a custom API and it should work.  

sport_path = football
league_path = cfl

**Comment by jasper502** [comment]
```
sensor:
  - platform: teamtracker
    sport_path: football
    league_path: cfl
    league_id: CFL
    team_id: SSK
    name: Roughriders
```
Am I missing something here?  Still doesn't work.
