### ISSUE TITLE
Can we add Belgian First Division A as well? 

### ISSUE THREAD

**Issue by schumi2309** [vasqued2/ha-teamtracker#37]
Hello,
Is it possible to add the Belgian football league first division? If yes, how ?

Thank you.

**Comment by vasqued2** [comment]
You can set it up as a Custom API Configuration.  
```
sport_path: soccer
league_path: bel.1
```

**Comment by schumi2309** [comment]
Ok, it works

And if I want the result of all the World Cup matches, is there a possibility without having to put a sensor for each team?

**Comment by vasqued2** [comment]
No.  One sensor per team.

**Comment by jrspowers** [comment]
hello i'm trying to create this sensor but it doesn't work well i put it in config.yaml this way but i don't get a new sensor?

```yaml
platform: teamtracker
sport_path: soccer
league_path: bel.1
name: jupiler_pro_league
```

**Comment by vasqued2** [comment]
You are missing the league_id and team_id.

```
- platform: teamtracker
  league_id: XXX
  team_id: GENK
  sport_path: soccer
  league_path: bel.1
  name: jupiler_pro_league
```

**Comment by jrspowers** [comment]
hello it works perfectly now i have a question i also want club brugge should i put it like this or else?

```yaml
configuration.yaml
platform: teamtracker
league_id: XXX
team_id: CLUB BRUGGE
sport_path: soccer
league_path: bel.1
name: jupiler_pro_league
```
